=== MrRyanTBaker/MrRyanTBaker.github.io/Info2351/week5/contents.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT contents (unit+) >
<!ELEMENT unit (numeral, title, start, sections) >
<!ELEMENT numeral (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT start (#PCDATA) >
<!ELEMENT sections (chapter+) >
<!ELEMENT chapter (number, name, page) >
<!ELEMENT number (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT page (#PCDATA) >
<!ATTLIST unit order CDATA #REQUIRED >
<!ATTLIST sections group CDATA #REQUIRED >

=== MrRyanTBaker/MrRyanTBaker.github.io/Info2351/week5/iot.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="transformation.xsl" type="text/xsl"?>
<!DOCTYPE contents SYSTEM "contents.dtd">
<!--Week 5 Transformation Project by Ryan Baker-->

<contents>

    <unit order="1">
        <numeral>I</numeral>
        <title>Introduction &amp; Concepts</title>
        <start>17</start>
        <sections group='1'>
            <chapter><number>1</number><name>Introduction to the Internet of Things</name><page>19</page></chapter>
            <chapter><number>1.1</number><name>Introduction</name><page>20</page></chapter>
            <chapter><number>1.1.1</number><name>Definition &amp; Characteristics of IoT</name><page>22</page></chapter>
            <chapter><number>1.2</number><name>Physical Design of IoT</name><page>24</page></chapter>
            <chapter><number>1.2.1</number><name>Things in IoT</name><page>24</page></chapter>
            <chapter><number>1.2.2</number><name>IoT Protocols</name><page>24</page></chapter>
            <chapter><number>1.3</number><name>Logical Design of IoT</name><page>31</page></chapter>
            <chapter><number>1.3.1</number><name>IoT Functional Blocks</name><page>31</page></chapter>
            <chapter><number>1.3.2</number><name>IoT Communication Models</name><page>31</page></chapter>
            <chapter><number>1.3.3</number><name>IoT Communication APIs</name><page>34</page></chapter>
            <chapter><number>1.4</number><name>IoT Enabling Technologies</name><page>38</page></chapter>
            <chapter><number>1.4.1</number><name>Wireless Sensor Networks</name><page>39</page></chapter>
            <chapter><number>1.4.2</number><name>Cloud Computing</name><page>39</page></chapter>
            <chapter><number>1.4.3</number><name>Big Data Analytics</name><page>40</page></chapter>
            <chapter><number>1.4.4</number><name>Communication Protocols</name><page>41</page></chapter>
            <chapter><number>1.4.5</number><name>Enbedded Systems</name><page>42</page></chapter>
            <chapter><number>1.5</number><name>IoT Levels &amp; Deployment Templates</name><page>42</page></chapter>
            <chapter><number>1.5.1</number><name>IoT Level-1</name><page>44</page></chapter>
            <chapter><number>1.5.2</number><name>IoT Level-1</name><page>44</page></chapter>
            <chapter><number>1.5.3</number><name>IoT Level-2</name><page>44</page></chapter>
            <chapter><number>1.5.4</number><name>IoT Level-3</name><page>46</page></chapter>
            <chapter><number>1.5.5</number><name>IoT Level-4</name><page>48</page></chapter>
            <chapter><number>1.5.6</number><name>IoT Level-5</name><page>49</page></chapter>        
            <chapter><number>2</number><name>Domain Specific IoTs</name><page>53</page></chapter> 
            <chapter><number>2.1</number><name>Introduction</name><page>54</page></chapter> 
            <chapter><number>2.2</number><name>Home Automation</name><page>54</page></chapter> 
            <chapter><number>2.2.1</number><name>Smart Lighting</name><page>54</page></chapter> 
            <chapter><number>2.2.2</number><name>Smart Appliances</name><page>54</page></chapter> 
            <chapter><number>2.2.3</number><name>Intrusion Detection</name><page>56</page></chapter> 
            <chapter><number>2.2.4</number><name>Smoke/Gas Detectors</name><page>56</page></chapter> 
            <chapter><number>2.3</number><name>Cities</name><page>56</page></chapter> 
            <chapter><number>2.3.1</number><name>Smart Parking</name><page>56</page></chapter> 
            <chapter><number>2.3.2</number><name>Smart Lighting</name><page>57</page></chapter> 
            <chapter><number>2.3.3</number><name>Smart Roads</name><page>58</page></chapter> 
            <chapter><number>2.3.4</number><name>Structural Health Monitoring</name><page>58</page></chapter> 
            <chapter><number>2.3.5</number><name>Surveillance</name><page>58</page></chapter> 
            <chapter><number>2.3.6</number><name>Emergency Response</name><page>58</page></chapter> 
            <chapter><number>2.4</number><name>Environment</name><page>59</page></chapter> 
            <chapter><number>2.4.1</number><name>Weather Monitoring</name><page>59</page></chapter> 
            <chapter><number>2.4.2</number><name>Air Pollution Monitoring</name><page>59</page></chapter> 
            <chapter><number>2.4.3</number><name>Noise Pollution Monitoring</name><page>60</page></chapter> 
            <chapter><number>2.4.4</number><name>Forest Fire Detection</name><page>61</page></chapter> 
            <chapter><number>2.4.5</number><name>River Floods Detection</name><page>61</page></chapter> 
            <chapter><number>2.5</number><name>Energy</name><page>61</page></chapter> 
            <chapter><number>2.5.1</number><name>Smart Grids</name><page>61</page></chapter> 
            <chapter><number>2.5.2</number><name>Renewable Energy Systems</name><page>62</page></chapter> 
            <chapter><number>2.5.3</number><name>Prognostics</name><page>62</page></chapter>
            <chapter><number>2.6</number><name>Retail</name><page>64</page></chapter>
            <chapter><number>2.6.1</number><name>Inventory Management</name><page>64</page></chapter>
            <chapter><number>2.6.2</number><name>Smart Payments</name><page>64</page></chapter>
            <chapter><number>2.6.3</number><name>Smart Vending Machines</name><page>64</page></chapter>
            <chapter><number>2.7</number><name>Logistics</name><page>65</page></chapter>
            <chapter><number>2.7.1</number><name>Route Generation and Scheduling</name><page>65</page></chapter>
            <chapter><number>2.7.2</number><name>Fleet Tracking</name><page>66</page></chapter>
            <chapter><number>2.7.3</number><name>Shipping Monitoring</name><page>66</page></chapter>
            <chapter><number>2.7.4</number><name>Remote Vehicle Diagnositcs</name><page>67</page></chapter>
            <chapter><number>2.8</number><name>Agriculture</name><page>68</page></chapter>
            <chapter><number>2.8.1</number><name>Smart Irrigation</name><page>68</page></chapter>
            <chapter><number>2.8.2</number><name>Green House Control</name><page>69</page></chapter>
            <chapter><number>2.9</number><name>Industry</name><page>69</page></chapter>
            <chapter><number>2.9.1</number><name>Machine Diagnosis &amp; Prognosis</name><page>69</page></chapter>
            <chapter><number>2.9.2</number><name>Indoor Air Quality Monitoring</name><page>70</page></chapter>
            <chapter><number>2.10</number><name>Health &amp; Lifestyle</name><page>71</page></chapter>
            <chapter><number>2.10.1</number><name>Health &amp; Fitness Monitoring</name><page>71</page></chapter>
            <chapter><number>2.10.2</number><name>Wearable Electronics</name><page>72</page></chapter>
            <chapter><number>3</number><name>IoT and M2M</name><page>75</page></chapter>
            <chapter><number>3.1</number><name>Introduction</name><page>76</page></chapter>
            <chapter><number>3.2</number><name>M2M</name><page>76</page></chapter>
            <chapter><number>3.3</number><name>Difference between IoT and M2M</name><page>77</page></chapter>
            <chapter><number>3.4</number><name>SDN and NFV for IoT</name><page>80</page></chapter>
            <chapter><number>3.4.1</number><name>Software Defined Networking</name><page>81</page></chapter>
            <chapter><number>3.4.2</number><name>Network Function Virtualization</name><page>85</page></chapter>
            <chapter><number>4</number><name>IoT System Management with NETCONF-YANG</name><page>91</page></chapter>
            <chapter><number>4.1</number><name>Need for IoT Systems Management</name><page>92</page></chapter>
            <chapter><number>4.2</number><name>Simple Network Management Protocol (SNMP)</name><page>93</page></chapter>
            <chapter><number>4.2.1</number><name>Limitations of SNMP</name><page>93</page></chapter>
            <chapter><number>4.3</number><name>Network Operator Requirements</name><page>94</page></chapter>
            <chapter><number>4.4</number><name>NETCONF</name><page>96</page></chapter>
            <chapter><number>4.5</number><name>YANG</name><page>97</page></chapter>
            <chapter><number>4.6</number><name>IoT Systems Management with NETCONF-YANG</name><page>106</page></chapter>
            <chapter><number>4.6.1</number><name>NETOPEER</name><page>107</page></chapter>
        </sections>
    </unit>
   
    <unit order="2">
        <numeral>II</numeral>
        <title>Developing Internet of Things</title>
        <start>111</start>
        <sections group='2'>
            <chapter><number>5</number><name>Introduction to the Internet of Things</name><page>113</page></chapter>
            <chapter><number>5.1</number><name>Introduction</name><page>114</page></chapter>   
            <chapter><number>5.2</number><name>IoT Design Methodology</name><page>114</page></chapter>   
            <chapter><number>5.2.1</number><name>Step 1: Purpose &amp; Requirements Specification</name><page>114</page></chapter>   
            <chapter><number>5.2.2</number><name>Step 2: Process Specification </name><page>116</page></chapter>   
            <chapter><number>5.2.3</number><name>Step 3: Domain Model Specification </name><page>117</page></chapter>   
            <chapter><number>5.2.4</number><name>Step 4: Information Model Specifications </name><page>119</page></chapter>   
            <chapter><number>5.2.5</number><name>Step 5: Service Specifications </name><page>119</page></chapter>   
            <chapter><number>5.2.6</number><name>Step 6: IoT Level Specifications </name><page>121</page></chapter>   
            <chapter><number>5.2.7</number><name>Step 7: Functional View Specification </name><page>121</page></chapter>
