=== MrRyanTBaker/MrRyanTBaker.github.io/Info2351/week5/validation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT year (planting, harvest) >
<!ELEMENT planting (season+) >
<!ELEMENT harvest (season+) >
<!ELEMENT season (month+) >
<!ELEMENT month (#PCDATA) >
<!ATTLIST season period CDATA #REQUIRED>

=== MrRyanTBaker/MrRyanTBaker.github.io/Info2351/week5/year.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="stylesheet.xsl" type="text/xsl"?>
<!DOCTYPE year SYSTEM "validation.dtd">
<year>
    <planting>
        <season period="spring">
            <month>March</month>
            <month>April</month>
            <month>May</month>
        </season>
        <season period="summer">
            <month>June</month>
            <month>July</month>
            <month>August</month>
        </season>
    </planting>
    <harvest>
        <season period="fall">
            <month>September</month>
            <month>October</month>
            <month>November</month>
        </season>
        <season period="winter">
            <month>December</month>
            <month>January</month>
            <month>February</month>
        </season>
    </harvest>
</year>
